# Converting mdb tables to csv files

In [ ]:
# ! wget https://files.isric.org/public/wise/WD-WISE.zip

--2021-01-18 13:40:58--  https://files.isric.org/public/wise/WD-WISE.zip
Resolving files.isric.org (files.isric.org)... 137.224.9.5
Connecting to files.isric.org (files.isric.org)|137.224.9.5|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3253519 (3.1M) [application/zip]
Saving to: ‘WD-WISE.zip.1’

WD-WISE.zip.1       100%[===================>]   3.10M   206KB/s    in 17s

2021-01-18 13:41:17 (190 KB/s) - ‘WD-WISE.zip.1’ saved [3253519/3253519]

In [ ]:
# ! unzip WD-WISE.zip

Archive:  WD-WISE.zip
   creating: ISRIC_report_2008_02/
  inflating: ISRIC_report_2008_02/ISRIC-WISE_ver3.mdb
  inflating: ISRIC_report_2008_02/ISRIC_Report_2008_02.pdf

In [ ]:
# ! brew install mdbtools
# ! pip install meza

In [ ]:
import os, io
import pandas as pd
import subprocess

In [ ]:
path_wisesoil = 'ISRIC_report_2008_02/ISRIC-WISE_ver3.mdb'

In [ ]:
table_names = subprocess.check_output(['mdb-tables', path_wisesoil])
table_names = table_names.decode().split()
table_names

['WISE3__ReadMeFirst',
 'WISE3_coding_conventions',
 'WISE3_HORIZON',
 'WISE3_LABcodes_Description',
 'WISE3_LABname',
 'WISE3_LABname_codes',
 'WISE3_SITE',
 'WISE3_SOURCE']

In [ ]:
dir_csv = 'ISRIC_report_2008_02_csv/'
os.makedirs(dir_csv, exist_ok=True)

In [ ]:
%%time

for table_name in table_names:
    
    table = subprocess.check_output(
        ['mdb-export', path_wisesoil, table_name])
    
    with open(f'{dir_csv}/{table_name}.csv', mode='w') as f:
        f.write(table.decode())

CPU times: user 16.2 ms, sys: 45.1 ms, total: 61.3 ms
Wall time: 1.98 s

In [ ]:
! ls ISRIC_report_2008_02_csv/

WISE3_HORIZON.csv              WISE3_SITE.csv
WISE3_LABcodes_Description.csv WISE3_SOURCE.csv
WISE3_LABname.csv              WISE3__ReadMeFirst.csv
WISE3_LABname_codes.csv        WISE3_coding_conventions.csv

In [ ]:
pd.read_csv('ISRIC_report_2008_02_csv/WISE3_SITE.csv')

,WISE3_id,ISO,DESCR,DATEYR,DATEMON,SOLDEP,HORNUM,FAO_90,PHA_90,FAO_74,...,LFORM,POSIT,SLOPE,PARMAT,DRAIN,LANDUS,SOURCE_ID,PITREF,LAB_ID,COUNTRY
0,AF0001,AF,3,1962.0,NaN,150,3,CLl,NaN,Bk,...,LV,LS,NaN,UC,W,AA4,AS3/73,Profile 16 p10-11.,AF01,Afghanistan
1,AF0002,AF,3,1962.0,NaN,170,4,FLc,NaN,Jc,...,LV,LS,NaN,UF,M,AA6,AS3/73,"Profile 20, pp 15-16.",AF01,Afghanistan
2,AF0003,AF,3,1962.0,NaN,110,3,FLc,NaN,Jc,...,LV,LO,NaN,UF,P,AA6,AS3/73,"Profile 41, pp 20-21.",AF01,Afghanistan
3,AF0004,AF,3,1962.0,NaN,270,6,SCg,NaN,Zo,...,LV,BO,NaN,UF,M,AA4,AS3/73,"Profile 17, pp 96-97.",AF01,Afghanistan
4,AF0005,AF,3,1962.0,NaN,190,6,SCk,NaN,Zo,...,LV,LO,NaN,UF,P,HE2,AS3/73,"Profile 21, pp 74-75.",AF01,Afghanistan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10248,ZW0063,ZW,2,1991.0,NaN,138,6,LXh,NaN,Lc,...,SH,CR,3,IB1,W,NaN,AF4/KM,"Pit 5E2, p. 136",ZW01,Zimbabwe
10249,ZW0064,ZW,2,1991.0,NaN,200,6,LXh,NaN,Lf,...,SH,NaN,NaN,IA1,W,U,AF4/KM,"Pit 5G2, P. 130",ZW01,Zimbabwe
10250,ZW0065,ZW,2,1991.0,NaN,68,4,PHl,NaN,Hl,...,LL,NaN,NaN,MB,W,AA4,AF4/KM,Pit 4PE2. p. 121,ZW01,Zimbabwe
10251,ZW0066,ZW,2,1991.0,NaN,92,3,VRe,NaN,Vp,...,LL,NaN,1,IB2,W,U,AF4/KM,"Pit 3B2, p. 112",ZW01,Zimbabwe
10252,ZW0067,ZW,1,1992.0,6.0,220,7,PTa,NaN,Ap,...,NaN,NaN,0,NaN,I,AA,ISIS-2005,ZW011_ISIS5,NL01,Zimbabwe

## Reference

- https://medium.com/@wenyu.z/reading-ms-access-mdb-files-on-mac-969a176baa7a